#grid 5 * 5

print("Susunan Kotak ")
print("[(1,1) ; (1,2) ; (1,4) ; (1,5)]")
print("[(2,1) ; (2,2) ; (2,4) ; (2,5)]")
print("[(3,1) ; (3,2) ; (3,4) ; (3,5)]")
print("[(4,1) ; (4,2) ; (4,4) ; (4,5)]")
print("[(5,1) ; (5,2) ; (5,4) ; (5,5)]")


satusatu = input("Masukkan Angka Kotak 1,1 = ")
print(type(satusatu))
a = int(satusatu)
satudua = input("Masukkan Angka Kotak 1,2 = ")
print(type(satudua))
b = int(satudua)
satutiga = input("Masukkan Angka Kotak 1,3 = ")
print(type(satutiga))
c = int(satutiga)
satuempat = input("Masukkan Angka Kotak 1,4 = ")
print(type(satuempat))
d = int(satuempat)
satulima = input("Masukkan Angka Kotak 1,5 = ")
print(type(satulima))
e = int(satulima)

duasatu = input("Masukkan Angka Kotak 2,1 = ")
print(type(duasatu))
f = int(duasatu)
duadua = input("Masukkan Angka Kotak 2,2 = ")
print(type(duadua))
g = int(duadua)
duatiga = input("Masukkan Angka Kotak 2,3 = ")
print(type(duatiga))
h = int(duatiga)
duaempat = input("Masukkan Angka Kotak 2,4 = ")
print(type(duaempat))
i = int(duaempat)
dualima = input("Masukkan Angka Kotak 2,5 = ")
print(type(dualima))
j = int(dualima)

tigasatu = input("Masukkan Angka Kotak 3,1 = ")
print(type(tigasatu))
k = int(tigasatu)
tigadua = input("Masukkan Angka Kotak 3,2 = ")
print(type(tigadua))
l = int(tigadua)
tigatiga = input("Masukkan Angka Kotak 3,3 = ")
print(type(tigatiga))
m = int(tigatiga)
tigaempat = input("Masukkan Angka Kotak 3,4 = ")
print(type(tigaempat))
n = int(tigaempat)
tigalima = input("Masukkan Angka Kotak 3,5 = ")
print(type(tigalima))
o = int(tigalima)

empatsatu = input("Masukkan Angka Kotak 4,1 = ")
print(type(empatsatu))
p = int(empatsatu)
empatdua = input("Masukkan Angka Kotak 4,2 = ")
print(type(empatdua))
q = int(empatdua)
empattiga = input("Masukkan Angka Kotak 4,3 = ")
print(type(empattiga))
r = int(empattiga)
empatempat = input("Masukkan Angka Kotak 4,4 = ")
print(type(empatempat))
s = int(empatempat)
empatlima = input("Masukkan Angka Kotak 4,5 = ")
print(type(empatlima))
t = int(empatlima)

limasatu = input("Masukkan Angka Kotak 5,1 = ")
print(type(limasatu))
u = int(limasatu)
limadua = input("Masukkan Angka Kotak 5,2 = ")
print(type(limadua))
v = int(limadua)
limatiga = input("Masukkan Angka Kotak 5,3 = ")
print(type(limatiga))
w = int(limatiga)
limaempat = input("Masukkan Angka Kotak 5,4 = ")
print(type(limaempat))
x = int(limaempat)
limalima = input("Masukkan Angka Kotak 5,5 = ")
print(type(limalima))
y = int(limalima)


SUM = input("Masukkan Total yang diinginkan : ")
print(type(SUM))
totalnilai = int(SUM)

grid = []
grid.append([a,b,c,d,e])
grid.append([f,g,h,i,j])
grid.append([k,l,m,n,o])
grid.append([p,q,r,s,t])
grid.append([u,v,w,x,y])